language: python

sudo: false

env:
    - CONDA="python=2.7"
    - CONDA="python=3.3"
    - CONDA="python=3.4"

before_install:
    - wget http://bit.ly/miniconda -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes
    - conda update --yes conda
    - conda info -a
    - travis_retry conda create -n test $CONDA pip jinja2 pandas mock six nose
    - source activate test
    - travis_retry pip install vincent
install:
    - python setup.py install

script:
    - cd tests && nosetests --verbose --nocapture folium_tests.py
