language: python

sudo: false

python:
    - 2.7
    - 3.4
    - 3.5

env:
    - TEST_TARGET=branca_release
    - TEST_TARGET=branca_latest
    - TEST_TARGET=coding_standards

before_install:
    - wget http://bit.ly/miniconda -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda update --yes --all
    - conda config --add channels conda-forge --force
    - conda create --yes -n TEST python=$TRAVIS_PYTHON_VERSION --file requirements.txt --file requirements-dev.txt
    - source activate TEST

    - if [[ "$TRAVIS_PYTHON_VERSION" != "3.5" ]]; then
        conda install --yes mock ;
      fi

# Test source distribution.
install:
    - python setup.py sdist && version=$(python setup.py --version) && pushd dist  && pip install folium-${version}.tar.gz && popd

script:
    - if [[ $TEST_TARGET == 'branca_release' ]]; then
        python setup.py test ;
      fi

    - if [[ $TEST_TARGET == 'branca_latest' ]]; then
        pip install git+https://github.com/python-visualization/branca.git ;
        python setup.py test ;
      fi

    - if [[ $TEST_TARGET == 'coding_standards' ]]; then
        find . -type f -name "*.py" ! -name 'conf.py' | xargs flake8 --max-line-length=100 ;
      fi
