language: python

sudo: false

notifications:
  email: false

matrix:
  fast_finish: true
  include:
    - python: 2.7
      env: TEST_TARGET=branca_release
    - python: 3.4
      env: TEST_TARGET=branca_release
    - python: 3.5
      env: TEST_TARGET=branca_release
  allow_failures:
    - python: 3.5
      env: TEST_TARGET=branca_latest
    - python: 3.4
      env: TEST_TARGET=branca_latest
    - python: 2.7
      env: TEST_TARGET=branca_latest

before_install:
    - wget http://bit.ly/miniconda -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda update --yes --all
    - conda config --add channels conda-forge --force
    - conda create --yes -n TEST python=$TRAVIS_PYTHON_VERSION --file requirements.txt --file requirements-dev.txt
    - source activate TEST

    - if [[ "$TRAVIS_PYTHON_VERSION" != "3.5" ]]; then
        conda install --yes mock ;
      fi

    - if [[ $TEST_TARGET == 'branca_latest' ]]; then
        pip install git+https://github.com/python-visualization/branca.git ;
      fi

# Test source distribution.
install:
    - python setup.py sdist && version=$(python setup.py --version) && pushd dist  && pip install folium-${version}.tar.gz && popd

script:
    - python setup.py test
    - find . -type f -name "*.py" ! -name 'conf.py' | xargs flake8 --max-line-length=100
